#!/usr/bin/env sh

#
# for this to work you must configure sudo such that
# it will be able to run the command without password
#
# see this wiki page for information:
#  - https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)#configure-scripting-addition
#
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa
#

# bsp or float (default: float)
yabai -m config \
  layout bsp \
  top_padding 16 \
  bottom_padding 16 \
  left_padding 16 \
  right_padding 16 \
  window_gap 16 \
  window_shadow float \
  focus_follows_mouse autoraise \
  insert_feedback_color 0x00d75f5f \
  active_window_border_color 0xff7aa2f7 \
  normal_window_border_color 0x80565f89 \
  window_border_width 3 \
  window_border_radius 0 \
  window_border_blur on \
  window_border_hidpi on \
  # external_bar all:35:0

yabai -m rule --add app="^System Settings$" sticky=on manage=off
yabai -m rule --add app="Calculator" sticky=on manage=off
yabai -m rule --add app="^Finder$" sticky=on manage=off
yabai -m rule --add app="^Disk Utility$" sticky=on manage=off
yabai -m rule --add app="^System Information$" sticky=on  manage=off
yabai -m rule --add app="^Activity Monitor$" sticky=on manage=off
yabai -m rule --add app="^Console$" manage=off
yabai -m rule --add app="^Digital Colou?r Meter$" sticky=on manage=off
yabai -m rule --add app="^Pomotroid$" manage=off
yabai -m rule --add app="^Font Book$" manage=off
