#!/usr/bin/env sh

#
# for this to work you must configure sudo such that
# it will be able to run the command without password
#
# see this wiki page for information:
#  - https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)#configure-scripting-addition
#
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa
#

# bsp or float (default: float)
yabai -m config \
  layout bsp \
  top_padding 12 \
  bottom_padding 12 \
  left_padding 12 \
  right_padding 12 \
  window_gap 12 \
  window_shadow float \
  # external_bar all:35:0

yabai -m rule --add app="^System Settings$" sticky=on manage=off
yabai -m rule --add app="Calculator" sticky=on manage=off
yabai -m rule --add app="^Finder$" sticky=on manage=off
yabai -m rule --add app="^Disk Utility$" sticky=on manage=off
yabai -m rule --add app="^System Information$" sticky=on  manage=off
yabai -m rule --add app="^Activity Monitor$" sticky=on manage=off
yabai -m rule --add app="^Console$" manage=off
yabai -m rule --add app="^Digital Colou?r Meter$" sticky=on manage=off
yabai -m rule --add app="^Pomotroid$" manage=off
yabai -m rule --add app="^Font Book$" manage=off
yabai -m rule --add app="Microsoft Teams" title="Microsoft Teams Notification" sticky=on manage=off
